### ISSUE TITLE
Set up codebase

### ISSUE THREAD

**Issue by JosephLaMantia** [CPG4/Habit-Pal#10]
Create codebase and ensure that the group all has access and knows how to properly work on different branches.

- [ ] Set up codebase on main branch and push to repo
- [ ] Group checks out their own development branch (using git checkout "(branch-name)"
- [ ] Group understands how to merge development branch into main branch

**Comment by YerBoySisi** [comment]
Create codebase and ensure that the group all has access and knows how to properly work on different branches.

- [x] Set up codebase on main branch and push to repo
- [x] Group checks out their own development branch (using git checkout "(branch-name)"
- [x] Group understands how to merge development branch into main branch
